services:
  - type: web
    name: gptads-api
    env: python
    plan: free  # ou starter, se quiser mais recursos
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
